# Generated by Django 5.1.2 on 2024-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
    ]
